version: "3.8"
services:
  frontend:
    image: reenasree/frontend
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    ports:
      - "3000:3000"
    networks:
      - fitmitra_network

  backend:
    image: reenasree/backend
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1G
    ports:
      - "5000:5000"
    networks:
      - fitmitra_network

networks:
  fitmitra_network:
    driver: overlay