version: "3.8"
services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - fitmitra_network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - fitmitra_network

networks:
  fitmitra_network:
    driver: bridge
