version: "3.8"
services:
  frontend:
    image: xanderbilla/frontend:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    ports:
      - "8000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - fitmitra_network
    depends_on:
      - backend

  backend:
    image: xanderbilla/backend:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "1"
          memory: 1G
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - fitmitra_network

networks:
  fitmitra_network:
    driver: overlay
