version: "3.8"
services:
  backend:
    image: reenasree/backend:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1G
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://kreenasree:bxXM94bqfLgPipDd@cluster0.dp8maob.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - fitmitra_network

  frontend:
    image: reenasree/frontend:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - fitmitra_network
    depends_on:
      - backend

networks:
  fitmitra_network:
    driver: overlay
